import os

BOT_TOKEN = os.environ.get("BOT_TOKEN", "")
CHAT_ID = os.environ.get("CHAT_ID", "")

# LinkedIn search — Mortgage / Loan / Financial Services titles
KEYWORDS = [
    # Financial Analyst (1–15)
    "Financial Analyst",
    "Senior Financial Analyst",
    "Junior Financial Analyst",
    "Financial Data Analyst",
    "Financial Modelling Analyst",
    "Financial Operations Analyst",
    "Financial Planning Analyst",
    "Financial Performance Analyst",
    "Financial Systems Analyst",
    "Financial Reporting Analyst",
    "Finance Analyst Banking",
    "Financial Services Analyst",
    "Investment Analyst Mortgage",
    "Treasury Analyst Banking",
    "FP&A Analyst Banking",
    # Loan / Credit (16–35)
    "Loan Analyst",
    "Senior Loan Analyst",
    "Credit Analyst",
    "Senior Credit Analyst",
    "Credit Risk Analyst",
    "Loan Operations Analyst",
    "Loan Documentation Analyst",
    "Loan Processing Analyst",
    "Loan Servicing Analyst",
    "Loan Portfolio Analyst",
    "Loan Origination Analyst",
    "Loan Underwriting Analyst",
    "Commercial Loan Analyst",
    "Retail Loan Analyst",
    "Consumer Loan Analyst",
    "Mortgage Loan Analyst",
    "Home Loan Analyst",
    "Housing Loan Analyst",
    "Credit Pack Analyst",
    "Credit Policy Analyst",
    # Mortgage-specific (36–55)
    "Mortgage Analyst",
    "Mortgage Operations Analyst",
    "Mortgage Underwriter",
    "Mortgage Loan Processor",
    "Mortgage Loan Officer",
    "Mortgage Servicing Analyst",
    "Mortgage Servicing Specialist",
    "Mortgage Banking Analyst",
    "Mortgage Compliance Analyst",
    "Mortgage Post Closer",
    "Mortgage Closer",
    "Mortgage Quality Analyst",
    "Mortgage Document Analyst",
    "Mortgage Risk Analyst",
    "Escrow Analyst",
    "Foreclosure Analyst",
    "Loss Mitigation Analyst",
    "Default Servicing Analyst",
    "HMDA Analyst",
    "MSR Analyst",
    # Compliance / Risk (56–70)
    "Compliance Analyst",
    "Senior Compliance Analyst",
    "Regulatory Compliance Analyst",
    "Risk Analyst",
    "Senior Risk Analyst",
    "Portfolio Risk Analyst",
    "Regulatory Affairs Analyst",
    "Internal Compliance Analyst",
    "Audit Analyst Banking",
    "SOX Compliance Analyst",
    "AML Analyst Banking",
    "KYC Analyst Banking",
    "Regulatory Reporting Analyst",
    "Compliance Officer Mortgage",
    "Risk Management Analyst",
    # Operations / MIS / Process (71–90)
    "Banking Operations Analyst",
    "Finance Operations Analyst",
    "MIS Analyst Banking",
    "Process Analyst Loan",
    "Quality Assurance Analyst Mortgage",
    "Operations Analyst Banking",
    "Senior Operations Analyst",
    "Document Analyst Loan",
    "Document Indexing Analyst",
    "Credit Pack Indexing Analyst",
    "PDF Processing Analyst",
    "Workflow Analyst Banking",
    "Process Associate Mortgage",
    "Senior Process Associate Loan",
    "Process Manager Mortgage",
    "Team Lead Loan Operations",
    "Operations Manager Mortgage",
    "Business Analyst Mortgage",
    "Data Analyst Loan Servicing",
    "Reporting Analyst Mortgage",
    # Company / servicer searches (91–105)
    "Wells Fargo Analyst",
    "Black Knight Analyst",
    "Cenlar Analyst",
    "LoanCare Analyst",
    "Mr Cooper Analyst",
    "Rocket Mortgage Analyst",
    "PHH Mortgage Analyst",
    "Nationstar Analyst",
    "PennyMac Analyst",
    "ServiceMac Analyst",
    "Mortgage Servicing",
    "Loan Servicing",
    "Mortgage Processing Hyderabad",
    "Loan Operations Hyderabad",
    "Mortgage Analyst Bangalore",
]

LOCATIONS = [
    "Hyderabad",
    "Bangalore",
    "Chennai",
    "Kochi",
    "Visakhapatnam",
    "Mumbai",
    "Pune",
    "Delhi",
    "Noida",
    "Gurgaon",
    "Ahmedabad",
    "Kolkata",
]

MAX_JOBS_PER_CYCLE = 15
PORTAL_KEYWORD_LIMIT = 20
LINKEDIN_KEYWORD_LIMIT = 40
LINKEDIN_LOCATION_LIMIT = 10
NAUKRI_JOBS_PER_SEARCH = 10
SCRAPE_WINDOW_SECONDS = 86400
MAX_ENRICH_PER_CYCLE = 50
CHECK_INTERVAL_LABEL = "1 hour"

PRIORITY_KEYWORDS = [
    "Mortgage Analyst",
    "Mortgage Loan Analyst",
    "Loan Analyst",
    "Credit Analyst",
    "Mortgage Servicing Analyst",
    "Mortgage Operations Analyst",
    "Loan Servicing Analyst",
    "Mortgage Underwriter",
    "Financial Analyst",
    "Mortgage Compliance Analyst",
    "Loan Operations Analyst",
    "Credit Risk Analyst",
    "Mortgage Quality Analyst",
    "Escrow Analyst",
    "Business Analyst Mortgage",
]
